### ISSUE TITLE
S3 연동 문제 확인

### ISSUE THREAD

**Issue by choitaedong2** [ClustProject/WSAutoMLMainWeb#19]
배포 환경에서 S3 업로드 실패

**Comment by 0-wook** [comment]
현 사용중인 태스크 정의
- admin: automl-main-web-task-definition:14
- user: automl-main-web-user-task-definition:4

**Comment by 0-wook** [comment]
태스크 정의 변경
- admin: automl-main-web-task-definition:14 → 15

**Comment by 0-wook** [comment]
태스크 정의 변경

- admin: automl-main-web-task-definition:15 → 16
- S3 연동 성공 확인
